Feat/us05/user account create
WildCodeSchool/2023-02-php-paris-p3-afac pull request #11
Opened 2023-07-17 14:52 UTC by Lozok25

Merci de revoir ma PR avec bcp de patience bisous

2023-07-17 14:54 UTC, ju-wd commented on assets/styles/app.scss
> +
ligne à supprimer

2023-07-17 14:55 UTC, ju-wd commented on assets/styles/app.scss
> +
ligne à supprimer

2023-07-17 14:55 UTC, ju-wd commented on assets/styles/app.scss
> +
ligne à supprimer

2023-07-17 14:55 UTC, ju-wd commented on assets/styles/app.scss
> +
ligne à supprimer

2023-07-17 14:58 UTC, ju-wd commented on config/packages/security.yaml
> +        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
laisser les simple quotes

2023-07-17 15:04 UTC, ju-wd requested changes

2023-07-17 15:04 UTC, ju-wd commented on src/Controller/SecurityController.php
> +        // get the login error if there is one
commentaires à supprimer

2023-07-17 15:04 UTC, ju-wd commented on src/DataFixtures/UserFixtures.php
> +        // $manager->flush();
commentaires à supprimer

2023-07-17 15:15 UTC, ju-wd approved these changes
Ok

2023-07-18 09:04 UTC, mickaellambert approved these changes

2023-07-18 09:04 UTC, mickaellambert commented on config/bundles.php
> +    SymfonyCasts\Bundle\VerifyEmail\SymfonyCastsVerifyEmailBundle::class => ['all' => true],
vous avez remis le emailverifier

2023-07-18 09:04 UTC, mickaellambert commented on src/Entity/User.php
> +    public const ROLES = [
pourquoi avoir mis une clé numérique en string ici ?

2023-07-18 12:17 UTC, mickaellambert approved these changes

2023-07-18 12:17 UTC, merged