Home page
WildCodeSchool/2023-02-php-paris-p3-afac pull request #5
Opened 2023-06-29 10:33 UTC by Lozok25

Attente retour PR

2023-06-29 11:51 UTC, ju-wd approved these changes
Ok

2023-07-05 07:57 UTC, ju-wd commented on assets/styles/app.scss
> +
Saut de ligne après * et espace avant les accolades

2023-07-05 07:57 UTC, ju-wd commented on assets/styles/app.scss
> +
Saut de ligne à supprimer

2023-07-05 07:59 UTC, ju-wd commented on assets/styles/app.scss
> +
A intégrer dans le sélecteur du dessus

2023-07-05 08:12 UTC, ju-wd requested changes

2023-07-05 08:12 UTC, ju-wd commented on assets/styles/app.scss
> +
A intégrer dans le sélecteur du dessus pour ne pas se répéter

2023-07-05 08:12 UTC, ju-wd commented on assets/styles/app.scss
> +
Idem, à intégrer sur le sélecteur du dessus

2023-07-05 08:12 UTC, ju-wd commented on assets/styles/app.scss
> +$font-family-base:'Gothic A1', sans-serif;
Variable $primary black à supprimer car doublon avec $primaryTextColor

2023-07-05 08:12 UTC, ju-wd commented on assets/styles/app.scss
Variable déjà déclarée, à supprimer

2023-07-05 08:12 UTC, ju-wd commented on templates/base.html.twig
> +
2 sauts de ligne à supprimer

2023-07-05 08:12 UTC, ju-wd commented on templates/base.html.twig
> +
Saut de ligne en trop

2023-07-05 08:12 UTC, ju-wd commented on templates/base.html.twig
> +
Saut de ligne à supprimer

2023-07-05 08:46 UTC, ju-wd approved these changes
Ok

2023-07-05 12:40 UTC, mickaellambert requested changes
- images de 1 a 19 et rien dautre

2023-07-05 13:26 UTC, mickaellambert approved these changes

2023-07-05 13:26 UTC, merged