CRUD Work et Technique fait
WildCodeSchool/2023-02-php-paris-p3-afac pull request #8
Opened 2023-07-06 12:15 UTC by VinchC

Les formulaires fonctionnent.
On peut créer une oeuvre, la modifier, la supprimer et uploader une image via Vich.
Les forms sont à compléter au niveau du contenu affiché (mise en place de placeholders, modification des labels qui sont en anglais)

2023-07-06 13:28 UTC, ju-wd commented on templates/work/index.html.twig
> +{% endblock %}
Tu peux supprimer le page work/index.html.twig

2023-07-06 13:28 UTC, ju-wd commented on templates/work/show.html.twig
> +{% endblock %}
Tu peux aussi supprimer aussi supprimer ce template

2023-07-06 14:25 UTC, ju-wd approved these changes
Ok !

2023-07-10 09:48 UTC, mickaellambert requested changes

2023-07-10 09:48 UTC, mickaellambert commented on templates/partials/_navbar.html.twig
> +					<a class="nav-link" href="/work">GALERIE</a>
{{ path() }}

2023-07-10 09:48 UTC, mickaellambert commented on migrations/Version20230706083247.php
> +        $this->addSql('ALTER TABLE work ADD updated_at DATETIME DEFAULT NULL');
Attention aux précédentes migrations, elles ont été supprimées

2023-07-10 09:48 UTC, mickaellambert commented on src/Controller/WorkController.php
> -    #[Route('/work/{techniqueName?}', name: 'technique_show', methods: ['GET'])]
A remettre via un pull de dev

2023-07-12 08:14 UTC, merged