Feat/s4 usv05/oeuvre
WildCodeSchool/2023-02-php-paris-p3-afac pull request #9
Opened 2023-07-10 13:49 UTC by ju-wd

2023-07-10 14:30 UTC, Lozok25 commented on assets/styles/app.scss
>  }
Supprimer  l'espace en trop :)

2023-07-10 14:31 UTC, Lozok25 commented on assets/styles/app.scss
>      }
suppression des ces doubles crochets :)

2023-07-10 14:38 UTC, Lozok25 commented on src/Controller/WorkController.php
>          ]);
Espace en trop :)

2023-07-10 14:44 UTC, Lozok25 approved these changes

2023-07-11 08:47 UTC, mickaellambert requested changes

2023-07-11 08:47 UTC, mickaellambert commented on src/Controller/WorkController.php
> +    #[Route('/work/show/{id}', name: 'app_work_show', methods: ['GET'])]
A quoi te sert d'avoir deux fois un show ? Au dessus c'est une route pour un show aussi non ?

2023-07-11 08:47 UTC, mickaellambert commented on templates/work/index.html.twig
> +					{# <img src="{{ vich_uploader_asset(work) }}" alt="{{ work.name }} class="img-thumbnail grayscale work-pictures"> #}
commentaire inutile non ?

2023-07-11 08:47 UTC, mickaellambert commented on templates/work/index.html.twig
> +					src="../build/images/{{ work.picture }}" class="img-thumbnail grayscale work-pictures">
utilise la fonction asset() de twig

2023-07-11 08:47 UTC, mickaellambert commented on templates/work/show.html.twig
> +				src="/build/images/{{ work.picture }}" class="img-thumbnail grayscale picture">
utilise la fonction asset() de twig

2023-07-11 08:47 UTC, mickaellambert commented on templates/work/show.html.twig
> +			{# <img src="{{ vich_uploader_asset(work) }}" alt="{{ work.name }} class="img-thumbnail grayscale work-pictures"> #}
commentaire inutile non ?

2023-07-11 08:47 UTC, mickaellambert commented on templates/work/show.html.twig
> +{# <a href="{{ path('app_work_edit', {'id': work.id}) }}">edit</a> #}
Commentaires ? qu'est ce donc ?

2023-07-11 09:56 UTC, ju-wd commented on src/Controller/WorkController.php
> +    #[Route('/work/show/{id}', name: 'app_work_show', methods: ['GET'])]
Je ne parviens pas a afficher la page de l'Oeuvre avec cette route 
    #[Route('/work/{id}', name: 'app_work_show', methods: ['GET'])]

2023-07-11 09:59 UTC, ju-wd commented on templates/work/index.html.twig
> +					{# <img src="{{ vich_uploader_asset(work) }}" alt="{{ work.name }} class="img-thumbnail grayscale work-pictures"> #}
Je l'ai retiré

2023-07-11 09:59 UTC, ju-wd commented on templates/work/index.html.twig
> +					src="../build/images/{{ work.picture }}" class="img-thumbnail grayscale work-pictures">
Fait

2023-07-11 09:59 UTC, ju-wd commented on templates/work/show.html.twig
> +				src="/build/images/{{ work.picture }}" class="img-thumbnail grayscale picture">
fait

2023-07-11 09:59 UTC, ju-wd commented on templates/work/show.html.twig
> +			{# <img src="{{ vich_uploader_asset(work) }}" alt="{{ work.name }} class="img-thumbnail grayscale work-pictures"> #}
Je l'ai retiré

2023-07-11 10:00 UTC, ju-wd commented on templates/work/show.html.twig
> +{# <a href="{{ path('app_work_edit', {'id': work.id}) }}">edit</a> #}
ne concerne pas mon us. je l'ai retiré

2023-07-11 11:30 UTC, mickaellambert commented on src/Controller/WorkController.php
> +    #[Route('/work/show/{id}', name: 'app_work_show', methods: ['GET'])]
Normal c'est la même route que celle du dessus, je te conseille de plutôt modifier la route du dessus /work/tecnique/{technique}

2023-07-11 12:49 UTC, ju-wd commented on src/Controller/WorkController.php
> +    #[Route('/work/show/{id}', name: 'app_work_show', methods: ['GET'])]
C'est ok c'est modifié

2023-07-12 07:30 UTC, mickaellambert approved these changes

2023-07-12 08:32 UTC, merged